// Module SG — jeu de données de démonstration (mock)
import type {
  Activity,
  ConformiteCheck,
  Deadline,
  DocType,
  GedCat,
  GedDoc,
  Member,
  SgData,
} from "./sg-types";

const DOC_TYPES: DocType[] = [
  { code: "BA", label: "Bulletin d'adhésion", required: true },
  { code: "CHARTE", label: "Charte du membre", required: true },
  { code: "CE", label: "Carte étudiante", required: true },
  { code: "RIB", label: "RIB", required: true },
  { code: "RC", label: "Attestation RC", required: true },
  { code: "CV", label: "CV à jour", required: false },
];

const GED_CATS: GedCat[] = [
  { id: "ba", label: "Bulletins d'adhésion", count: 0 },
  { id: "cr", label: "Comptes rendus (CR)", count: 0 },
  { id: "pvag", label: "PV d'Assemblée Générale", count: 0 },
  { id: "ri", label: "Règlement intérieur", count: 0 },
  { id: "statuts", label: "Statuts", count: 0 },
  { id: "pref", label: "Préfecture", count: 0 },
  { id: "compta", label: "Comptabilité", count: 0 },
  { id: "contrats", label: "Contrats & conventions", count: 0 },
];

const MEMBERS: Member[] = [
  {
    id: "lb",
    first: "Léa",
    last: "Bertrand",
    initials: "LB",
    role: "Secrétaire Générale",
    pole: "Bureau",
    promo: 2026,
    year: "M1",
    status: "active",
    email: "lea.bertrand@jeece.fr",
    phone: "06 12 45 78 90",
    joined: "sept. 2023",
    city: "Lille",
    address: "12 rue de la Digue, 59000 Lille",
    studentId: "21804512",
    jeeceId: "JEE-2326-014",
    birth: "2003-04-18",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "ok", RC: "ok", CV: "ok" },
    mandates: [
      { role: "Secrétaire Générale", period: "2025 – 2026", current: true },
      { role: "Resp. Communication", period: "2024 – 2025" },
    ],
  },
  {
    id: "tm",
    first: "Thomas",
    last: "Moreau",
    initials: "TM",
    role: "Président",
    pole: "Bureau",
    promo: 2026,
    year: "M1",
    status: "active",
    email: "thomas.moreau@jeece.fr",
    phone: "06 98 32 11 76",
    joined: "sept. 2023",
    city: "Lille",
    address: "5 avenue des Saules, 59800 Lille",
    studentId: "21803987",
    jeeceId: "JEE-2326-001",
    birth: "2003-01-09",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "ok", RC: "ok", CV: "ok" },
    mandates: [
      { role: "Président", period: "2025 – 2026", current: true },
      { role: "Resp. Commercial", period: "2024 – 2025" },
    ],
  },
  {
    id: "cd",
    first: "Camille",
    last: "Dubois",
    initials: "CD",
    role: "Trésorière",
    pole: "Trésorerie",
    promo: 2026,
    year: "M1",
    status: "active",
    email: "camille.dubois@jeece.fr",
    phone: "07 61 22 09 14",
    joined: "sept. 2023",
    city: "Roubaix",
    studentId: "21804120",
    jeeceId: "JEE-2326-002",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "ok", RC: "pending", CV: "ok" },
    mandates: [{ role: "Trésorière", period: "2025 – 2026", current: true }],
  },
  {
    id: "ng",
    first: "Nicolas",
    last: "Garcia",
    initials: "NG",
    role: "Resp. Systèmes d'Information",
    pole: "SI",
    promo: 2027,
    year: "L3",
    status: "active",
    email: "nicolas.garcia@jeece.fr",
    phone: "06 44 87 65 23",
    joined: "oct. 2024",
    city: "Lille",
    studentId: "22805631",
    jeeceId: "JEE-2426-021",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "pending", RC: "missing", CV: "ok" },
    mandates: [{ role: "Resp. SI", period: "2025 – 2026", current: true }],
  },
  {
    id: "el",
    first: "Emma",
    last: "Laurent",
    initials: "EL",
    role: "Resp. Communication",
    pole: "Communication",
    promo: 2027,
    year: "L3",
    status: "active",
    email: "emma.laurent@jeece.fr",
    phone: "07 52 18 44 90",
    joined: "oct. 2024",
    city: "Villeneuve-d'Ascq",
    studentId: "22804998",
    jeeceId: "JEE-2426-022",
    docs: { BA: "ok", CHARTE: "ok", CE: "pending", RIB: "ok", RC: "ok", CV: "missing" },
  },
  {
    id: "hp",
    first: "Hugo",
    last: "Petit",
    initials: "HP",
    role: "Resp. Commercial",
    pole: "Commercial",
    promo: 2027,
    year: "L3",
    status: "active",
    email: "hugo.petit@jeece.fr",
    phone: "06 27 90 31 58",
    joined: "oct. 2024",
    city: "Lille",
    studentId: "22805012",
    jeeceId: "JEE-2426-023",
    docs: { BA: "ok", CHARTE: "pending", CE: "ok", RIB: "ok", RC: "ok", CV: "ok" },
  },
  {
    id: "sr",
    first: "Sarah",
    last: "Roux",
    initials: "SR",
    role: "Chargée de mission Qualité",
    pole: "Qualité",
    promo: 2028,
    year: "L2",
    status: "active",
    email: "sarah.roux@jeece.fr",
    phone: "07 88 12 65 47",
    joined: "oct. 2025",
    city: "Lille",
    studentId: "23806740",
    jeeceId: "JEE-2526-038",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "missing", RC: "missing", CV: "missing" },
  },
  {
    id: "mf",
    first: "Maxime",
    last: "Fontaine",
    initials: "MF",
    role: "Chargé d'affaires",
    pole: "Commercial",
    promo: 2028,
    year: "L2",
    status: "pending",
    email: "maxime.fontaine@jeece.fr",
    phone: "06 70 45 12 88",
    joined: "mai 2026",
    city: "Lille",
    studentId: "23807155",
    docs: { BA: "pending", CHARTE: "missing", CE: "missing", RIB: "missing", RC: "missing", CV: "missing" },
  },
  {
    id: "ja",
    first: "Julie",
    last: "André",
    initials: "JA",
    role: "Chargée de communication",
    pole: "Communication",
    promo: 2028,
    year: "L2",
    status: "pending",
    email: "julie.andre@jeece.fr",
    phone: "07 14 09 76 32",
    joined: "mai 2026",
    city: "Lille",
    docs: { BA: "pending", CHARTE: "pending", CE: "missing", RIB: "missing", RC: "missing", CV: "missing" },
  },
  {
    id: "rl",
    first: "Romain",
    last: "Leroy",
    initials: "RL",
    role: "Membre Alumni",
    pole: "Bureau",
    promo: 2024,
    year: "Diplômé",
    status: "alumni",
    email: "romain.leroy@alumni.jeece.fr",
    phone: "06 33 21 09 87",
    joined: "sept. 2021",
    city: "Paris",
    docs: { BA: "ok", CHARTE: "ok", CE: "ok", RIB: "ok", RC: "ok", CV: "ok" },
    mandates: [
      { role: "Président", period: "2023 – 2024" },
      { role: "Trésorier", period: "2022 – 2023" },
    ],
  },
  {
    id: "cb",
    first: "Chloé",
    last: "Blanc",
    initials: "CB",
    role: "Membre actif",
    pole: "SI",
    promo: 2028,
    year: "L2",
    status: "inactive",
    email: "chloe.blanc@jeece.fr",
    phone: "—",
    joined: "oct. 2025",
    city: "Lens",
    docs: { BA: "ok", CHARTE: "missing", CE: "missing", RIB: "missing", RC: "missing", CV: "missing" },
  },
];

const DEADLINES: Deadline[] = [
  { id: "dl1", date: "2026-06-05", title: "Déclaration en préfecture", sub: "Changement de bureau 2025-2026", kind: "Préfecture" },
  { id: "dl2", date: "2026-06-22", title: "Assemblée Générale Ordinaire", sub: "Convocation + ordre du jour à envoyer", kind: "Statutaire" },
  { id: "dl3", date: "2026-06-30", title: "Clôture comptable de l'exercice", sub: "Remise des justificatifs à la trésorerie", kind: "Comptabilité" },
  { id: "dl4", date: "2026-07-15", title: "Renouvellement assurance RC", sub: "Attestation MAIF à actualiser", kind: "Assurance" },
  { id: "dl5", date: "2026-09-10", title: "Campagne d'adhésion 2026-2027", sub: "Ouverture des bulletins d'adhésion", kind: "Adhésions" },
];

const CONFORMITE: ConformiteCheck[] = [
  { id: "c1", k: "Statuts à jour", s: "Dernière version validée en AG", state: "ok", ref: "STAT-2025-01" },
  { id: "c2", k: "Règlement intérieur", s: "Conforme aux statuts en vigueur", state: "ok", ref: "RI-2025-01" },
  { id: "c3", k: "Déclaration des dirigeants", s: "Bureau 2025-2026 à déclarer en préfecture", state: "pending", ref: "PREF-2026-04" },
  { id: "c4", k: "Assurance responsabilité civile", s: "Attestation à renouveler avant juillet", state: "pending", ref: "RC-2026" },
  { id: "c5", k: "Registre spécial", s: "Tenue du registre des modifications", state: "todo", ref: null },
  { id: "c6", k: "Procès-verbal de la dernière AG", s: "À rédiger et archiver après l'AGO", state: "todo", ref: null },
];

const DOCS: GedDoc[] = [
  {
    id: "g1",
    title: "Statuts de l'association — version 2025",
    cat: "statuts",
    pages: 8,
    format: "PDF",
    size: "412 Ko",
    mandat: "25–26",
    ref: "STAT-2025-01",
    status: "signed",
    author: "tm",
    signers: ["Thomas Moreau", "Léa Bertrand"],
    date: "14 mars 2025",
    dateAbs: "2025-03-14",
    tags: ["statuts", "officiel"],
    security: "Public",
    fav: true,
  },
  {
    id: "g2",
    title: "Règlement intérieur 2025-2026",
    cat: "ri",
    pages: 5,
    format: "PDF",
    size: "286 Ko",
    mandat: "25–26",
    ref: "RI-2025-01",
    status: "signed",
    author: "lb",
    signers: ["Léa Bertrand"],
    date: "20 sept. 2025",
    dateAbs: "2025-09-20",
    tags: ["règlement", "interne"],
    security: "Interne",
  },
  {
    id: "g3",
    title: "PV — Assemblée Générale Ordinaire 2025",
    cat: "pvag",
    pages: 4,
    format: "PDF",
    size: "198 Ko",
    mandat: "25–26",
    ref: "PV-AG-2025-01",
    status: "archived",
    author: "lb",
    signers: ["Léa Bertrand", "Thomas Moreau"],
    date: "28 nov. 2025",
    dateAbs: "2025-11-28",
    tags: ["ag", "pv"],
    security: "Interne",
  },
  {
    id: "g4",
    title: "CR — Réunion de bureau #07",
    cat: "cr",
    pages: 2,
    format: "PDF",
    size: "94 Ko",
    mandat: "25–26",
    ref: "CR-2026-07",
    status: "signed",
    author: "lb",
    signers: ["Léa Bertrand"],
    date: "12 mai 2026",
    dateAbs: "2026-05-12",
    tags: ["bureau", "réunion"],
    security: "Interne",
    fav: true,
  },
  {
    id: "g5",
    title: "CR — Réunion de bureau #08",
    cat: "cr",
    pages: 3,
    format: "PDF",
    size: "112 Ko",
    mandat: "25–26",
    ref: "CR-2026-08",
    status: "pending",
    author: "lb",
    signers: [],
    date: "2 juin 2026",
    dateAbs: "2026-06-02",
    tags: ["bureau", "réunion"],
    security: "Interne",
  },
  {
    id: "g6",
    title: "Convention de partenariat — Decathlon",
    cat: "contrats",
    pages: 6,
    format: "PDF",
    size: "521 Ko",
    mandat: "25–26",
    ref: "CONV-2026-03",
    status: "signed",
    author: "hp",
    signers: ["Hugo Petit", "Thomas Moreau"],
    date: "18 avr. 2026",
    dateAbs: "2026-04-18",
    tags: ["partenariat", "commercial"],
    security: "Confidentiel",
  },
  {
    id: "g7",
    title: "Bilan comptable — exercice 2024-2025",
    cat: "compta",
    pages: 7,
    format: "XLSX",
    size: "76 Ko",
    mandat: "25–26",
    ref: "COMPTA-2025-02",
    status: "archived",
    author: "cd",
    signers: ["Camille Dubois"],
    date: "10 janv. 2026",
    dateAbs: "2026-01-10",
    tags: ["comptabilité", "bilan"],
    security: "Confidentiel",
  },
  {
    id: "g8",
    title: "Récépissé de déclaration — Préfecture du Nord",
    cat: "pref",
    pages: 1,
    format: "PDF",
    size: "58 Ko",
    mandat: "24–25",
    ref: "PREF-2024-01",
    status: "archived",
    author: "tm",
    signers: [],
    date: "5 oct. 2024",
    dateAbs: "2024-10-05",
    tags: ["préfecture", "officiel"],
    security: "Public",
  },
  {
    id: "g9",
    title: "Bulletin d'adhésion — modèle 2026-2027",
    cat: "ba",
    pages: 2,
    format: "PDF",
    size: "88 Ko",
    mandat: "25–26",
    ref: "BA-2026-00",
    status: "pending",
    author: "lb",
    signers: [],
    date: "8 juin 2026",
    dateAbs: "2026-06-08",
    tags: ["adhésion", "modèle"],
    security: "Public",
  },
];

const ACTIVITY: Activity[] = [
  { who: "lb", action: "a validé", target: "RIB · Camille Dubois", ctx: "dossier membre", when: "il y a 2 h", icon: "checkmark-circle-02", tone: "brand" },
  { who: "lb", action: "a déposé", target: "CR — Réunion de bureau #08", ctx: "catégorie Comptes rendus", when: "hier", icon: "upload-04", tone: "info" },
  { who: "hp", action: "a signé", target: "Convention de partenariat — Decathlon", ctx: "signature numérique · Hugo Petit", when: "il y a 2 j", icon: "pen-tool", tone: "violet" },
  { who: "lb", action: "a créé le dossier de", target: "Maxime Fontaine", ctx: "nouveau membre", when: "il y a 3 j", icon: "user-add", tone: "brand" },
  { who: "lb", action: "a créé le dossier de", target: "Julie André", ctx: "nouveau membre", when: "il y a 3 j", icon: "user-add", tone: "brand" },
  { who: "cd", action: "a archivé", target: "Bilan comptable — exercice 2024-2025", ctx: "GED", when: "il y a 5 j", icon: "archive", tone: "neutral" },
  { who: "lb", action: "a ajouté une échéance", target: "Assemblée Générale Ordinaire", ctx: "calendrier réglementaire", when: "il y a 1 sem.", icon: "calendar-add-01", tone: "info" },
];

export function buildSeed(): SgData {
  // structuredClone évite que les mutations touchent les constantes de module
  return structuredClone({
    members: MEMBERS,
    docs: DOCS,
    deadlines: DEADLINES,
    conformite: CONFORMITE,
    docTypes: DOC_TYPES,
    gedCats: GED_CATS,
    activity: ACTIVITY,
  });
}
