ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "titre" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "email_statut" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "email_secondaire" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "telephone_mobile" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "telephone_corporate" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "telephone_direct" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "ville" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "region" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "pays" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "seniorite" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "departements" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "twitter" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "facebook" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "github" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "site_web" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "linkedin_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "effectifs" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "mots_cles" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "technologies" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "chiffre_affaires" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "annee_fondation" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "adresse_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "ville_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "region_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "pays_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "code_postal_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "telephone_entreprise" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "entreprise_pour_emails" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "apollo_contact_id" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "apollo_account_id" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "etape_apollo" text;--> statement-breakpoint
ALTER TABLE "crm"."prospect" ADD COLUMN IF NOT EXISTS "proprietaire_apollo" text;
